project:
  type: book
  output-dir: ../docs

book:
  title: "Dynamics of Youth"
  subtitle: "DATA HANDBOOK"
  author: "Neha Moopen"
  date: last-modified
  search: true
  repo-url: https://github.com/UtrechtUniversity/doy-data-handbook
  repo-actions: [edit]
  downloads: [docx]
  sidebar: 
    style: docked
  chapters:
    - index.qmd
    - definitions.qmd
    - data-management-plans.qmd
    - data-flow-diagrams.qmd
    - naming-conventions.qmd
    - pipelining.qmd
    - metadata.qmd
    - documentation.qmd
    - codebooks.qmd
    - storage.qmd
    - archiving.qmd
    - publication.qmd
    - governance.qmd
    - sharing.qmd
    - fair-data-cheatsheet.qmd
    - references.qmd
    - part: APPENDIX
      chapters: 
        - trainings.qmd
        - presentations.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, styles/theme-light.scss]
      dark: [cosmo, styles/theme-dark.scss]
#  pdf:
 #   documentclass: scrreprt
  docx: default


