project:
  type: book
  output-dir: ../docs

book:
  title: "Dynamics of Youth"
  subtitle: "DATA HANDBOOK"
  author: "Neha Moopen"
  date: last-modified
  search: true
  repo-url: https://github.com/UtrechtUniversity/doy-data-handbook
  repo-actions: [edit]
  downloads: [docx]
  sidebar: 
    style: docked
    collapse-level: 1
  chapters:
    - index.qmd
    - definitions.qmd
    - fair-data-cheatsheet.qmd
    - part: "PLAN & FUND"
      chapters:
        - data-management-plans.qmd
        - privacy-and-security.qmd
        - costs.qmd
        - data-flow-diagrams.qmd
    - part: "COLLECT & ANALYZE"
      chapters:
        - naming-conventions.qmd
        - folder-structures.qmd
        - preferred-formats.qmd
        - pipelining.qmd
        - metadata.qmd
        - documentation.qmd
        - codebooks.qmd
        - reproducibility.qmd
    - part: "PRESERVE & STORE"
      chapters:  
        - storage.qmd
        - archiving.qmd
    - part: "PUBLISH & SHARE"
      chapters:
        - governance.qmd
        - publication.qmd
        - transfer.qmd
    - part: "DISCOVER & REUSE"
      chapters:  
        - searching.qmd
    - references.qmd
    - part: "APPENDIX"
      chapters:
        - trainings.qmd
        - presentations.qmd

bibliography: references.bib

format:
  html:
    theme: 
      light: [cosmo, styles/theme-light.scss]
      dark: [cosmo, styles/theme-dark.scss]

